inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Style/Documentation:
  Include:
    - "lib/**/*"

Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/SignalException:
  EnforcedStyle: 'only_raise'
